# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 't.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 291, 211))
        self.groupBox.setObjectName("groupBox")
        self.wash_mode_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.wash_mode_lineEdit.setGeometry(QtCore.QRect(90, 110, 191, 20))
        self.wash_mode_lineEdit.setObjectName("wash_mode_lineEdit")
        self.Provice = QtWidgets.QLabel(self.groupBox)
        self.Provice.setGeometry(QtCore.QRect(13, 20, 71, 20))
        self.Provice.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Provice.setObjectName("Provice")
        self.city_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.city_lineEdit.setGeometry(QtCore.QRect(90, 50, 61, 20))
        self.city_lineEdit.setObjectName("city_lineEdit")
        self.City = QtWidgets.QLabel(self.groupBox)
        self.City.setGeometry(QtCore.QRect(13, 50, 71, 20))
        self.City.setObjectName("City")
        self.Wash_Mode = QtWidgets.QLabel(self.groupBox)
        self.Wash_Mode.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.Wash_Mode.setObjectName("Wash_Mode")
        self.site_id_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.site_id_lineEdit.setGeometry(QtCore.QRect(90, 140, 113, 20))
        self.site_id_lineEdit.setObjectName("site_id_lineEdit")
        self.province_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.province_lineEdit.setGeometry(QtCore.QRect(90, 20, 61, 20))
        self.province_lineEdit.setObjectName("province_lineEdit")
        self.Wash_Type = QtWidgets.QLabel(self.groupBox)
        self.Wash_Type.setGeometry(QtCore.QRect(10, 80, 71, 20))
        self.Wash_Type.setObjectName("Wash_Type")
        self.ssh_port_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ssh_port_lineEdit.setGeometry(QtCore.QRect(90, 170, 113, 20))
        self.ssh_port_lineEdit.setObjectName("ssh_port_lineEdit")
        self.Site_ID = QtWidgets.QLabel(self.groupBox)
        self.Site_ID.setGeometry(QtCore.QRect(10, 140, 71, 20))
        self.Site_ID.setObjectName("Site_ID")
        self.SSH_Port = QtWidgets.QLabel(self.groupBox)
        self.SSH_Port.setGeometry(QtCore.QRect(10, 170, 71, 20))
        self.SSH_Port.setObjectName("SSH_Port")
        self.wash_type_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.wash_type_lineEdit.setGeometry(QtCore.QRect(90, 80, 113, 20))
        self.wash_type_lineEdit.setObjectName("wash_type_lineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 10, 401, 331))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.camerazs_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.camerazs_port_lineEdit.setGeometry(QtCore.QRect(320, 186, 61, 20))
        self.camerazs_port_lineEdit.setObjectName("camerazs_port_lineEdit")
        self.in_label = QtWidgets.QLabel(self.groupBox_2)
        self.in_label.setGeometry(QtCore.QRect(11, 108, 48, 16))
        self.in_label.setObjectName("in_label")
        self.wepay_3 = QtWidgets.QLabel(self.groupBox_2)
        self.wepay_3.setGeometry(QtCore.QRect(11, 290, 36, 16))
        self.wepay_3.setObjectName("wepay_3")
        self.out = QtWidgets.QLabel(self.groupBox_2)
        self.out.setGeometry(QtCore.QRect(11, 134, 48, 16))
        self.out.setObjectName("out")
        self.wepay = QtWidgets.QLabel(self.groupBox_2)
        self.wepay.setGeometry(QtCore.QRect(11, 264, 48, 16))
        self.wepay.setObjectName("wepay")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(330, 21, 24, 16))
        self.label_4.setObjectName("label_4")
        self.doorled_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.doorled_checkBox.setGeometry(QtCore.QRect(98, 162, 35, 16))
        self.doorled_checkBox.setObjectName("doorled_checkBox")
        self.washing_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.washing_port_lineEdit.setGeometry(QtCore.QRect(320, 290, 61, 20))
        self.washing_port_lineEdit.setObjectName("washing_port_lineEdit")
        self.gateout_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.gateout_ip_lineEdit.setGeometry(QtCore.QRect(152, 134, 133, 20))
        self.gateout_ip_lineEdit.setObjectName("gateout_ip_lineEdit")
        self.doorled_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.doorled_port_lineEdit.setGeometry(QtCore.QRect(320, 160, 61, 20))
        self.doorled_port_lineEdit.setObjectName("doorled_port_lineEdit")
        self.cameraled_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.cameraled_port_lineEdit.setGeometry(QtCore.QRect(320, 212, 61, 20))
        self.cameraled_port_lineEdit.setObjectName("cameraled_port_lineEdit")
        self.gs_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.gs_port_lineEdit.setGeometry(QtCore.QRect(320, 238, 61, 20))
        self.gs_port_lineEdit.setObjectName("gs_port_lineEdit")
        self.washing_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.washing_ip_lineEdit.setGeometry(QtCore.QRect(152, 290, 133, 20))
        self.washing_ip_lineEdit.setObjectName("washing_ip_lineEdit")
        self.washing_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.washing_checkBox.setGeometry(QtCore.QRect(98, 292, 35, 16))
        self.washing_checkBox.setObjectName("washing_checkBox")
        self.doorout_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.doorout_checkBox.setGeometry(QtCore.QRect(98, 84, 35, 16))
        self.doorout_checkBox.setObjectName("doorout_checkBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(190, 21, 36, 16))
        self.label_3.setObjectName("label_3")
        self.Door_3 = QtWidgets.QLabel(self.groupBox_2)
        self.Door_3.setGeometry(QtCore.QRect(11, 160, 42, 16))
        self.Door_3.setObjectName("Door_3")
        self.cameraled_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.cameraled_checkBox.setGeometry(QtCore.QRect(98, 214, 35, 16))
        self.cameraled_checkBox.setObjectName("cameraled_checkBox")
        self.Door_4 = QtWidgets.QLabel(self.groupBox_2)
        self.Door_4.setGeometry(QtCore.QRect(11, 212, 54, 16))
        self.Door_4.setObjectName("Door_4")
        self.wpc_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.wpc_checkBox.setGeometry(QtCore.QRect(98, 266, 35, 16))
        self.wpc_checkBox.setObjectName("wpc_checkBox")
        self.doorled_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.doorled_ip_lineEdit.setGeometry(QtCore.QRect(152, 160, 133, 20))
        self.doorled_ip_lineEdit.setObjectName("doorled_ip_lineEdit")
        self.gateout_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.gateout_port_lineEdit.setGeometry(QtCore.QRect(320, 134, 61, 20))
        self.gateout_port_lineEdit.setObjectName("gateout_port_lineEdit")
        self.camerazs_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.camerazs_checkBox.setGeometry(QtCore.QRect(98, 188, 35, 16))
        self.camerazs_checkBox.setObjectName("camerazs_checkBox")
        self.digan = QtWidgets.QLabel(self.groupBox_2)
        self.digan.setGeometry(QtCore.QRect(11, 238, 24, 16))
        self.digan.setObjectName("digan")
        self.wepay_5 = QtWidgets.QLabel(self.groupBox_2)
        self.wepay_5.setGeometry(QtCore.QRect(11, 186, 48, 16))
        self.wepay_5.setObjectName("wepay_5")
        self.doorin_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.doorin_checkBox.setEnabled(True)
        self.doorin_checkBox.setGeometry(QtCore.QRect(98, 58, 35, 16))
        self.doorin_checkBox.setObjectName("doorin_checkBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(90, 21, 48, 16))
        self.label_2.setObjectName("label_2")
        self.gatein_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.gatein_port_lineEdit.setGeometry(QtCore.QRect(320, 108, 61, 20))
        self.gatein_port_lineEdit.setObjectName("gatein_port_lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(11, 21, 48, 16))
        self.label.setObjectName("label")
        self.gatein_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.gatein_ip_lineEdit.setGeometry(QtCore.QRect(152, 108, 133, 20))
        self.gatein_ip_lineEdit.setObjectName("gatein_ip_lineEdit")
        self.gs_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.gs_checkBox.setGeometry(QtCore.QRect(98, 240, 35, 16))
        self.gs_checkBox.setObjectName("gs_checkBox")
        self.wpc_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.wpc_ip_lineEdit.setGeometry(QtCore.QRect(152, 264, 133, 20))
        self.wpc_ip_lineEdit.setObjectName("wpc_ip_lineEdit")
        self.Door_2 = QtWidgets.QLabel(self.groupBox_2)
        self.Door_2.setGeometry(QtCore.QRect(11, 82, 60, 16))
        self.Door_2.setObjectName("Door_2")
        self.doorout_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.doorout_ip_lineEdit.setGeometry(QtCore.QRect(152, 82, 133, 20))
        self.doorout_ip_lineEdit.setObjectName("doorout_ip_lineEdit")
        self.cameraled_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.cameraled_ip_lineEdit.setGeometry(QtCore.QRect(152, 212, 133, 20))
        self.cameraled_ip_lineEdit.setObjectName("cameraled_ip_lineEdit")
        self.doorin_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.doorin_ip_lineEdit.setGeometry(QtCore.QRect(152, 56, 133, 20))
        self.doorin_ip_lineEdit.setObjectName("doorin_ip_lineEdit")
        self.camerazs_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.camerazs_ip_lineEdit.setGeometry(QtCore.QRect(152, 186, 133, 20))
        self.camerazs_ip_lineEdit.setObjectName("camerazs_ip_lineEdit")
        self.doorin_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.doorin_port_lineEdit.setGeometry(QtCore.QRect(320, 56, 61, 20))
        self.doorin_port_lineEdit.setObjectName("doorin_port_lineEdit")
        self.gateout_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.gateout_checkBox.setGeometry(QtCore.QRect(98, 136, 35, 16))
        self.gateout_checkBox.setObjectName("gateout_checkBox")
        self.gs_ip_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.gs_ip_lineEdit.setGeometry(QtCore.QRect(152, 238, 133, 20))
        self.gs_ip_lineEdit.setObjectName("gs_ip_lineEdit")
        self.doorout_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.doorout_port_lineEdit.setGeometry(QtCore.QRect(320, 82, 61, 20))
        self.doorout_port_lineEdit.setObjectName("doorout_port_lineEdit")
        self.Door = QtWidgets.QLabel(self.groupBox_2)
        self.Door.setGeometry(QtCore.QRect(11, 56, 60, 16))
        self.Door.setObjectName("Door")
        self.wpc_port_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.wpc_port_lineEdit.setGeometry(QtCore.QRect(320, 264, 61, 20))
        self.wpc_port_lineEdit.setObjectName("wpc_port_lineEdit")
        self.gatein_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.gatein_checkBox.setGeometry(QtCore.QRect(98, 110, 35, 16))
        self.gatein_checkBox.setObjectName("gatein_checkBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 240, 291, 181))
        self.textBrowser.setObjectName("textBrowser")
        self.msg_label = QtWidgets.QLabel(self.centralwidget)
        self.msg_label.setGeometry(QtCore.QRect(390, 340, 289, 38))
        self.msg_label.setScaledContents(False)
        self.msg_label.setObjectName("msg_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(390, 390, 291, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.init_pushButton = QtWidgets.QPushButton(self.widget)
        self.init_pushButton.setObjectName("init_pushButton")
        self.horizontalLayout.addWidget(self.init_pushButton)
        self.read_setting_pushButton = QtWidgets.QPushButton(self.widget)
        self.read_setting_pushButton.setObjectName("read_setting_pushButton")
        self.horizontalLayout.addWidget(self.read_setting_pushButton)
        self.write_setting_pushButton = QtWidgets.QPushButton(self.widget)
        self.write_setting_pushButton.setObjectName("write_setting_pushButton")
        self.horizontalLayout.addWidget(self.write_setting_pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "配置工具"))
        self.groupBox.setTitle(_translate("MainWindow", "系统参数"))
        self.Provice.setText(_translate("MainWindow", "省份"))
        self.City.setText(_translate("MainWindow", "城市"))
        self.Wash_Mode.setText(_translate("MainWindow", "洗车模式"))
        self.Wash_Type.setText(_translate("MainWindow", "洗车机型"))
        self.Site_ID.setText(_translate("MainWindow", "站点编码"))
        self.SSH_Port.setText(_translate("MainWindow", "SSH端口号"))
        self.groupBox_2.setTitle(_translate("MainWindow", "设备参数"))
        self.in_label.setText(_translate("MainWindow", "进口闸机"))
        self.wepay_3.setText(_translate("MainWindow", "洗车机"))
        self.out.setText(_translate("MainWindow", "出口闸机"))
        self.wepay.setText(_translate("MainWindow", "微信扫码"))
        self.label_4.setText(_translate("MainWindow", "端口"))
        self.doorled_checkBox.setText(_translate("MainWindow", "有"))
        self.washing_checkBox.setText(_translate("MainWindow", "有"))
        self.doorout_checkBox.setText(_translate("MainWindow", "有"))
        self.label_3.setText(_translate("MainWindow", "IP地址"))
        self.Door_3.setText(_translate("MainWindow", "DoorLED"))
        self.cameraled_checkBox.setText(_translate("MainWindow", "有"))
        self.Door_4.setText(_translate("MainWindow", "CameraLED"))
        self.wpc_checkBox.setText(_translate("MainWindow", "有"))
        self.camerazs_checkBox.setText(_translate("MainWindow", "有"))
        self.digan.setText(_translate("MainWindow", "地感"))
        self.wepay_5.setText(_translate("MainWindow", "摄像头ZS"))
        self.doorin_checkBox.setText(_translate("MainWindow", "有"))
        self.label_2.setText(_translate("MainWindow", "是否有效"))
        self.label.setText(_translate("MainWindow", "设备名称"))
        self.gs_checkBox.setText(_translate("MainWindow", "有"))
        self.Door_2.setText(_translate("MainWindow", "出口卷闸门"))
        self.gateout_checkBox.setText(_translate("MainWindow", "有"))
        self.Door.setText(_translate("MainWindow", "入口卷闸门"))
        self.gatein_checkBox.setText(_translate("MainWindow", "有"))
        self.msg_label.setText(_translate("MainWindow", "提示信息"))
        self.init_pushButton.setText(_translate("MainWindow", "数据库初始化"))
        self.read_setting_pushButton.setText(_translate("MainWindow", "读取设置"))
        self.write_setting_pushButton.setText(_translate("MainWindow", "保存设置"))
        self.menu.setTitle(_translate("MainWindow", "配置工具"))

