# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 't.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.read_setting_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.read_setting_pushButton.setGeometry(QtCore.QRect(510, 530, 71, 31))
        self.read_setting_pushButton.setObjectName("read_setting_pushButton")
        self.write_setting_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.write_setting_pushButton.setGeometry(QtCore.QRect(620, 530, 71, 31))
        self.write_setting_pushButton.setObjectName("write_setting_pushButton")
        self.init_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.init_pushButton.setGeometry(QtCore.QRect(380, 530, 91, 31))
        self.init_pushButton.setObjectName("init_pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 290, 291, 181))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 10, 331, 211))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 291, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Door = QtWidgets.QLabel(self.layoutWidget)
        self.Door.setObjectName("Door")
        self.gridLayout.addWidget(self.Door, 0, 0, 1, 1)
        self.doorin_yes_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.doorin_yes_checkBox.setEnabled(True)
        self.doorin_yes_checkBox.setObjectName("doorin_yes_checkBox")
        self.gridLayout.addWidget(self.doorin_yes_checkBox, 0, 1, 1, 1)
        self.wepay_5 = QtWidgets.QLabel(self.layoutWidget)
        self.wepay_5.setObjectName("wepay_5")
        self.gridLayout.addWidget(self.wepay_5, 0, 2, 1, 1)
        self.camerazs_yes_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.camerazs_yes_checkBox.setObjectName("camerazs_yes_checkBox")
        self.gridLayout.addWidget(self.camerazs_yes_checkBox, 0, 3, 1, 1)
        self.Door_2 = QtWidgets.QLabel(self.layoutWidget)
        self.Door_2.setObjectName("Door_2")
        self.gridLayout.addWidget(self.Door_2, 1, 0, 1, 1)
        self.doorout_yes_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.doorout_yes_checkBox.setObjectName("doorout_yes_checkBox")
        self.gridLayout.addWidget(self.doorout_yes_checkBox, 1, 1, 1, 1)
        self.Door_4 = QtWidgets.QLabel(self.layoutWidget)
        self.Door_4.setObjectName("Door_4")
        self.gridLayout.addWidget(self.Door_4, 1, 2, 1, 1)
        self.cameraled_yes_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.cameraled_yes_checkBox.setObjectName("cameraled_yes_checkBox")
        self.gridLayout.addWidget(self.cameraled_yes_checkBox, 1, 3, 1, 1)
        self.in_label = QtWidgets.QLabel(self.layoutWidget)
        self.in_label.setObjectName("in_label")
        self.gridLayout.addWidget(self.in_label, 2, 0, 1, 1)
        self.gatein_yes_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.gatein_yes_checkBox.setObjectName("gatein_yes_checkBox")
        self.gridLayout.addWidget(self.gatein_yes_checkBox, 2, 1, 1, 1)
        self.digan = QtWidgets.QLabel(self.layoutWidget)
        self.digan.setObjectName("digan")
        self.gridLayout.addWidget(self.digan, 2, 2, 1, 1)
        self.groundsense_yes_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.groundsense_yes_checkBox.setObjectName("groundsense_yes_checkBox")
        self.gridLayout.addWidget(self.groundsense_yes_checkBox, 2, 3, 1, 1)
        self.out = QtWidgets.QLabel(self.layoutWidget)
        self.out.setObjectName("out")
        self.gridLayout.addWidget(self.out, 3, 0, 1, 1)
        self.gateout_yes_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.gateout_yes_checkBox.setObjectName("gateout_yes_checkBox")
        self.gridLayout.addWidget(self.gateout_yes_checkBox, 3, 1, 1, 1)
        self.wepay = QtWidgets.QLabel(self.layoutWidget)
        self.wepay.setObjectName("wepay")
        self.gridLayout.addWidget(self.wepay, 3, 2, 1, 1)
        self.wpc_yes_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.wpc_yes_checkBox.setObjectName("wpc_yes_checkBox")
        self.gridLayout.addWidget(self.wpc_yes_checkBox, 3, 3, 1, 1)
        self.Door_3 = QtWidgets.QLabel(self.layoutWidget)
        self.Door_3.setObjectName("Door_3")
        self.gridLayout.addWidget(self.Door_3, 4, 0, 1, 1)
        self.doorled_yes_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.doorled_yes_checkBox.setObjectName("doorled_yes_checkBox")
        self.gridLayout.addWidget(self.doorled_yes_checkBox, 4, 1, 1, 1)
        self.wepay_3 = QtWidgets.QLabel(self.layoutWidget)
        self.wepay_3.setObjectName("wepay_3")
        self.gridLayout.addWidget(self.wepay_3, 4, 2, 1, 1)
        self.washing_yes_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.washing_yes_checkBox.setObjectName("washing_yes_checkBox")
        self.gridLayout.addWidget(self.washing_yes_checkBox, 4, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 291, 271))
        self.groupBox.setObjectName("groupBox")
        self.washingport_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.washingport_lineEdit.setGeometry(QtCore.QRect(90, 230, 113, 20))
        self.washingport_lineEdit.setObjectName("washingport_lineEdit")
        self.wash_mode_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.wash_mode_lineEdit.setGeometry(QtCore.QRect(90, 110, 191, 20))
        self.wash_mode_lineEdit.setObjectName("wash_mode_lineEdit")
        self.Provice = QtWidgets.QLabel(self.groupBox)
        self.Provice.setGeometry(QtCore.QRect(13, 20, 71, 20))
        self.Provice.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Provice.setObjectName("Provice")
        self.washingIP_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.washingIP_lineEdit.setGeometry(QtCore.QRect(90, 200, 113, 20))
        self.washingIP_lineEdit.setObjectName("washingIP_lineEdit")
        self.city_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.city_lineEdit.setGeometry(QtCore.QRect(90, 50, 113, 20))
        self.city_lineEdit.setObjectName("city_lineEdit")
        self.City = QtWidgets.QLabel(self.groupBox)
        self.City.setGeometry(QtCore.QRect(13, 50, 71, 20))
        self.City.setObjectName("City")
        self.Wash_Mode = QtWidgets.QLabel(self.groupBox)
        self.Wash_Mode.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.Wash_Mode.setObjectName("Wash_Mode")
        self.site_id_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.site_id_lineEdit.setGeometry(QtCore.QRect(90, 140, 113, 20))
        self.site_id_lineEdit.setObjectName("site_id_lineEdit")
        self.wepay_4 = QtWidgets.QLabel(self.groupBox)
        self.wepay_4.setGeometry(QtCore.QRect(10, 230, 71, 20))
        self.wepay_4.setObjectName("wepay_4")
        self.wepay_2 = QtWidgets.QLabel(self.groupBox)
        self.wepay_2.setGeometry(QtCore.QRect(10, 200, 71, 20))
        self.wepay_2.setObjectName("wepay_2")
        self.province_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.province_lineEdit.setGeometry(QtCore.QRect(90, 20, 113, 20))
        self.province_lineEdit.setObjectName("province_lineEdit")
        self.Wash_Type = QtWidgets.QLabel(self.groupBox)
        self.Wash_Type.setGeometry(QtCore.QRect(10, 80, 71, 20))
        self.Wash_Type.setObjectName("Wash_Type")
        self.ssh_port_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ssh_port_lineEdit.setGeometry(QtCore.QRect(90, 170, 113, 20))
        self.ssh_port_lineEdit.setObjectName("ssh_port_lineEdit")
        self.wash_type_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.wash_type_lineEdit.setGeometry(QtCore.QRect(90, 80, 113, 20))
        self.wash_type_lineEdit.setObjectName("wash_type_lineEdit")
        self.Site_ID = QtWidgets.QLabel(self.groupBox)
        self.Site_ID.setGeometry(QtCore.QRect(10, 140, 71, 20))
        self.Site_ID.setObjectName("Site_ID")
        self.SSH_Port = QtWidgets.QLabel(self.groupBox)
        self.SSH_Port.setGeometry(QtCore.QRect(10, 170, 71, 20))
        self.SSH_Port.setObjectName("SSH_Port")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "配置工具"))
        self.read_setting_pushButton.setText(_translate("MainWindow", "读取设置"))
        self.write_setting_pushButton.setText(_translate("MainWindow", "保存设置"))
        self.init_pushButton.setText(_translate("MainWindow", "数据库初始化"))
        self.groupBox_2.setTitle(_translate("MainWindow", "设备状态"))
        self.Door.setText(_translate("MainWindow", "入口卷闸门"))
        self.doorin_yes_checkBox.setText(_translate("MainWindow", "有"))
        self.wepay_5.setText(_translate("MainWindow", "摄像头ZS"))
        self.camerazs_yes_checkBox.setText(_translate("MainWindow", "有"))
        self.Door_2.setText(_translate("MainWindow", "出口卷闸门"))
        self.doorout_yes_checkBox.setText(_translate("MainWindow", "有"))
        self.Door_4.setText(_translate("MainWindow", "CameraLED"))
        self.cameraled_yes_checkBox.setText(_translate("MainWindow", "有"))
        self.in_label.setText(_translate("MainWindow", "进口闸机"))
        self.gatein_yes_checkBox.setText(_translate("MainWindow", "有"))
        self.digan.setText(_translate("MainWindow", "地感"))
        self.groundsense_yes_checkBox.setText(_translate("MainWindow", "有"))
        self.out.setText(_translate("MainWindow", "出口闸机"))
        self.gateout_yes_checkBox.setText(_translate("MainWindow", "有"))
        self.wepay.setText(_translate("MainWindow", "微信扫码"))
        self.wpc_yes_checkBox.setText(_translate("MainWindow", "有"))
        self.Door_3.setText(_translate("MainWindow", "DoorLED"))
        self.doorled_yes_checkBox.setText(_translate("MainWindow", "有"))
        self.wepay_3.setText(_translate("MainWindow", "洗车机"))
        self.washing_yes_checkBox.setText(_translate("MainWindow", "有"))
        self.groupBox.setTitle(_translate("MainWindow", "洗车机配置"))
        self.Provice.setText(_translate("MainWindow", "省份"))
        self.City.setText(_translate("MainWindow", "城市"))
        self.Wash_Mode.setText(_translate("MainWindow", "洗车模式"))
        self.wepay_4.setText(_translate("MainWindow", "洗车机端口号"))
        self.wepay_2.setText(_translate("MainWindow", "洗车机IP"))
        self.Wash_Type.setText(_translate("MainWindow", "洗车机型"))
        self.Site_ID.setText(_translate("MainWindow", "站点编码"))
        self.SSH_Port.setText(_translate("MainWindow", "SSH端口号"))
        self.menu.setTitle(_translate("MainWindow", "配置工具"))

